server:
    port: 8080
    servlet:
        context-path: /santander

spring:
    datasource:
        driver-class-name: org.postgresql.Driver
        url: jdbc:postgresql://localhost:5432/postgres
        username: postgres
        password: c412f5bb
    jpa:
        show-sql: true
        database-platform: org.hibernate.dialect.PostgreSQLDialect
        generate-ddl: false
        hibernate:
            ddl-auto: none

application:
    description: Projeto criado para o Santander DevWeek
    version: 1.00
    termsOfService: http://swagger.io/terms/
    license:
        name: Apache 2.0
        url: http://springdoc.org/

